main : main.o
	gcc main.o -o main
	@echo 'creating main from .o files'

main.o = main.c
	gcc -c main.c -o main.o
	@echo 'creating main from .o files'




# .PHONY : all
#
# CC=gcc
#
# all : %.o
# 	$(CC) $^ -o $@
# 	@echo 'creating main from .o files'
#
# %.o: %.c
# 	$(CC) -c $< -o $@
# 	@echo 'creating main from .o files'
#
# clean:
# 	rm -rf main
